// Code generated by goctl. DO NOT EDIT.
package types

type SocialInfo struct {
	SocialType string `json:"social_type,options=[twitter]"`
	Uuid       string `json:"uuid"`
}

type UserInfo struct {
	Id                   int64        `json:"id,default=0"`
	Username             string       `json:"username"`
	Email                string       `json:"email"`
	Avatar               string       `json:"avatar,optional"`
	WalletAddress        string       `json:"walletAddress"`
	PrimaryWalletAddress string       `json:"primaryWalletAddress"`
	State                int          `json:"state,default=0"`
	FollowingCount       int          `json:"following_count"`
	FollowerCount        int          `json:"follower_count"`
	Social               []SocialInfo `json:"social"`
}

type ReplyStatus struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserLoginReq struct {
	LoginType     string `form:"login_type,options=wallet|twitter,default=wallet"`
	WalletAddress string `form:"wallet_address,optional"`
	Email         string `form:"email,optional"`
	WalletSign    string `header:"wallet_sign,optional"`
	Nonce         string `form:"nonce,optional"`
	SocialType    string `form:"social_type,options=[twitter],optional"`
	SocialId      string `form:"social_id,optional"`
}

type UserInfoReply struct {
	UserInfo
	Code        int    `json:"code"`
	Msg         int    `json:"msg"`
	AccessToken string `json:"access_token,omitempty"`
}

type CaptchaReq struct {
	WalletAddress string `json:"walletAddress"`
	Timestamp     int64  `json:"ts"`
}

type CaptchaReply struct {
	ReplyStatus
	Nonce string `json:"nonce"`
}

type AccountReq struct {
	WalletAddress string `path:"walletAddress"`
}

type UserSettingReq struct {
	Username             string `json:"username,optional"`
	WalletAddress        string `json:"walletAddress,optional"`
	Email                string `json:"email,optional"`
	Avatar               string `json:"avatar,optional"`
	PrimaryWalletAddress string `json:"primaryWalletAddress,optional"`
}

type NotificationReply struct {
	ReplyStatus
}

type UserFollowingReq struct {
	Userid string `path:"user_id"`
}

type UserFollowingReply struct {
	ReplyStatus
	Users []UserInfo `json:"users"`
}

type UserFollowerReq struct {
	Uuid string `path:"id"`
}

type UserFollowerReply struct {
	ReplyStatus
	Users []UserInfo `json:"users"`
}

type LikeReq struct {
	Uuid string `path:"id"`
	Type string `path:"type,options=contract|token|feed|all"`
}

type LikeReply struct {
	ReplyStatus
	Type        string   `path:"type,options=contract|token|feed|all"`
	AddressList []string `json:"address_list"`
}

type MetricContractReply struct {
	ReplyStatus
}

type MetricTokenReply struct {
	ReplyStatus
}

type FeedsListReq struct {
	Period int64 `json:"period,optional"`
}

type FeedsListReply struct {
	ReplyStatus
}

type CommentInfo struct {
	Id        int64  `json:"id"`
	TopicId   int64  `json:"topic_id"`
	TopicType int64  `json:"topic_type,options=contract|token|feed|all"`
	ReplyId   int64  `json:"reply_id"`
	ReplyType int64  `json:"reply_type,options=comment|reply"`
	FromUser  string `json:"from_user"`
	Content   string `json:"content"`
	LikeCount int64  `json:"like_count"`
	Date      int64  `json:"date"`
}

type CommentListReq struct {
	TopicId   string `path:"topic_id"`
	TopicType string `path:"topic_type"`
}

type CommentDeleteReq struct {
	Comment_id string `path:"comment_id"`
}

type CommentListReply struct {
	ReplyStatus
	Comments []CommentInfo `json:"comments"`
}

type SearchInfo struct {
	Address string  `json:"address"`
	Score   float32 `json:"score"`
}

type SearchReq struct {
	Query string `form:"q"`
	Type  string `form:"type,options=contract|token|address|all,default=all"`
}

type SearchReply struct {
	ReplyStatus
	SearchInfo []SearchInfo `json:"search_info"`
}
